### ISSUE TITLE
Get ready to put the tracker online

### ISSUE THREAD

**Issue by FreshAlacrity** [FreshAlacrity/front-tracker#4]
- [x] make a space for the token variable in the global data
- [x] allow entering the token by prompt or by URL parameter: https://www.w3schools.com/js/tryit.asp?filename=tryjs_prompt
- [x] make a URL parameter or other way to "forget" the stored data 
- [x] save the token locally
- [x] cache loaded data so export.js isn't needed
